import React, { useState } from "react";
import "../App.css";
import { api } from "../services/api";
import { Download, CheckCircle, CreditCard, ArrowLeft } from "lucide-react";

export default function InvoiceDetailPage({ invoice, onNavigate }) {
  const current = invoice || {
    id: "INV-1042",
    customer: "Acme Corp",
    amount: "₹2,73,000",
    status: "Unpaid",
    dueDate: "Sep 10",
    type: "One-Time"
  };

  const [paid, setPaid] = useState(current?.status === "Paid" || current?.status === "PAID");
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState(null);

  const handleRecordPayment = async () => {
    setLoading(true);
    try {
      if (current._id) {
        await api.invoices.recordPayment(current._id, {
          amount: current.rawAmount || 273000,
          method: "MANUAL",
          reference: `REC-${Date.now().toString().slice(-6)}`
        });
      }
      setPaid(true);
      setMessage({ type: "success", text: `Payment of ${current.amount} recorded successfully. Deal marked as Paid!` });
    } catch (err) {
      console.warn("Offline fallback for payment:", err.message);
      setPaid(true);
      setMessage({ type: "success", text: `Payment recorded locally. Status updated to Paid.` });
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadInvoice = () => {
    if (current._id) {
      const pdfUrl = `http://localhost:5000/api/v1/invoices/${current._id}/pdf`;
      window.open(pdfUrl, '_blank');
    } else {
      // Print-friendly invoice window for demonstration
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(`
          <html>
            <head>
              <title>Invoice - ${current.id}</title>
              <style>
                body { font-family: 'Segoe UI', Tahoma, sans-serif; padding: 40px; color: #2d3748; }
                .header { border-bottom: 2px solid #714b67; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; }
                h1 { color: #714b67; margin: 0; }
                .badge { background: ${paid ? '#299b45' : '#e53e3e'}; color: white; padding: 6px 14px; border-radius: 4px; font-weight: bold; }
                table { width: 100%; border-collapse: collapse; margin-top: 30px; }
                th, td { border: 1px solid #e2e8f0; padding: 12px; text-align: left; }
                th { background: #f7fafc; }
                .total { text-align: right; font-size: 18px; font-weight: bold; margin-top: 20px; }
              </style>
            </head>
            <body>
              <div class="header">
                <div>
                  <h1>DealFlow360 Invoice</h1>
                  <p>Tax Invoice / Delivery Note</p>
                </div>
                <div>
                  <h2>${current.id}</h2>
                  <span class="badge">${paid ? 'PAID' : 'UNPAID'}</span>
                </div>
              </div>
              <p><strong>Billed To:</strong> ${current.customer}</p>
              <p><strong>Due Date:</strong> ${current.dueDate || 'Net 30'}</p>
              <p><strong>Type:</strong> ${current.type || 'One-Time'}</p>
              <table>
                <thead>
                  <tr><th>Description</th><th>Qty</th><th>Amount</th></tr>
                </thead>
                <tbody>
                  <tr><td>Enterprise Hardware & Software Bundle</td><td>1</td><td>${current.amount}</td></tr>
                </tbody>
              </table>
              <div class="total">Total Due: ${current.amount}</div>
              <p style="margin-top: 50px; font-size: 12px; color: #718096;">Generated by DealFlow360 Quote-to-Cash Platform</p>
            </body>
          </html>
        `);
        printWindow.document.close();
        printWindow.focus();
        setTimeout(() => printWindow.print(), 500);
      }
    }
  };

  return (
    <main className="content">
      <div className="page-card">
        <div className="page-header">
          <div className="page-header-left">
            <span className="ops-label">Invoice Detail</span>
            <h1>Invoice Detail: {current.id} ({current.customer})</h1>
            <p className="subtitle">Audit invoice ledger, payment reconciliation, and tax documentation.</p>
          </div>
          <button className="btn-outline" onClick={() => onNavigate && onNavigate("invoices")} style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
            <ArrowLeft size={16} /> Back to Invoices
          </button>
        </div>

        {message && (
          <div style={{
            padding: "12px 16px",
            borderRadius: "8px",
            marginBottom: "18px",
            background: "#f0fdf4",
            border: "1px solid #86efac",
            color: "#166534",
            fontWeight: 500,
            fontSize: "14px",
            display: "flex",
            alignItems: "center",
            gap: "8px"
          }}>
            <CheckCircle size={18} />
            {message.text}
          </div>
        )}

        <div className="horizontal-timeline">
          <div className="timeline-node done">Order Confirmed</div>
          <div className="timeline-node done">Shipped</div>
          <div className={`timeline-node ${paid ? "done" : "current"}`}>Invoiced</div>
          <div className={`timeline-node ${paid ? "done" : ""}`}>Paid</div>
        </div>

        <div className="table-wrapper" style={{ marginTop: "24px" }}>
          <table>
            <thead>
              <tr>
                <th>Invoice #</th>
                <th>Amount</th>
                <th>Status</th>
                <th>Due Date</th>
                <th>Type</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td style={{ fontWeight: 600 }}>{current.id}</td>
                <td style={{ fontWeight: 600 }}>{current.amount}</td>
                <td>
                  <span className={`badge ${paid ? "green" : "red"}`}>
                    {paid ? "Paid" : "Unpaid"}
                  </span>
                </td>
                <td>{current.dueDate}</td>
                <td>{current.type || "One-Time"}</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="button-row" style={{ marginTop: "24px", display: 'flex', gap: '12px' }}>
          {!paid ? (
            <button className="btn-primary" onClick={handleRecordPayment} disabled={loading} style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
              <CreditCard size={16} />
              <span>Record Payment</span>
            </button>
          ) : (
            <button className="btn-primary" disabled style={{ background: '#299b45', borderColor: '#299b45', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <CheckCircle size={16} />
              <span>Payment Captured</span>
            </button>
          )}
          <button className="btn-outline" onClick={handleDownloadInvoice} style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
            <Download size={16} />
            <span>Download Invoice (PDF)</span>
          </button>
        </div>

        <div className="info-box" style={{ marginTop: "20px" }}>
          Partial invoicing stays reconciled with partial delivery, waiting to bill future shipments. Download Invoice streams the immutable PDF audit record.
        </div>
      </div>
    </main>
  );
}
